apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-volume-demo-storage-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data-stateful-0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-volume-demo-storage-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data-stateful-1"
